{{- if or .Values.config.owiPass .Values.config.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xg2g.fullname" . }}
  labels:
    {{- include "xg2g.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.owiPass }}
  owi-password: {{ .Values.config.owiPass | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.apiToken }}
  api-token: {{ .Values.config.apiToken | b64enc | quote }}
  {{- end }}
{{- end }}
