global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'xg2g'
    static_configs:
      - targets: ['host.docker.internal:9090']
        labels:
          instance: 'xg2g-main'
